sudo: required
dist: trusty
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
cache: bundler
addons:
  chrome: stable
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: bundle exec rake $RAKE_TASK
env:
  - RAKE_TASK=features:watir
